set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR AMD64)
set(CMAKE_C_COMPILER /tmp/compositor-parent-qt-windows/llvm-mingw-20260908-ucrt-macos-universal/bin/x86_64-w64-mingw32-clang)
set(CMAKE_CXX_COMPILER /tmp/compositor-parent-qt-windows/llvm-mingw-20260908-ucrt-macos-universal/bin/x86_64-w64-mingw32-clang++)
set(CMAKE_RC_COMPILER /tmp/compositor-parent-qt-windows/llvm-mingw-20260908-ucrt-macos-universal/bin/x86_64-w64-mingw32-windres)
set(CMAKE_FIND_ROOT_PATH /tmp/compositor-parent-ai-windows/sdk/onnxruntime-win-x64-1.30.0 /tmp/compositor-parent-qt-windows/llvm-mingw-20260908-ucrt-macos-universal/x86_64-w64-mingw32)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
