"""Generate owned codec fixtures; checks consume committed files without Python."""
import ctypes as c
import gzip
import json
from pathlib import Path
import struct
import zlib
from PIL import Image, ImageOps
import PIL

root = Path(__file__).parent / 'fixtures'
root.mkdir(exist_ok=True)
records = []

def chunk(kind, data):
    return struct.pack('>I', len(data)) + kind + data + struct.pack('>I', zlib.crc32(kind + data))

def png(width, height, pixels, profile=None):
    result = b'\x89PNG\r\n\x1a\n' + chunk(b'IHDR', struct.pack('>IIBBBBB', width, height, 8, 6, 0, 0, 0))
    if profile:
        result += chunk(b'iCCP', b'linear RGB\0\0' + zlib.compress(profile))
    rows = b''.join(b'\0' + pixels[y*width*4:(y+1)*width*4] for y in range(height))
    return result + chunk(b'IDAT', zlib.compress(rows)) + chunk(b'IEND', b'')

def reference(name, width, height, rgba, tolerance=0):
    raw = bytearray(rgba)
    for i in range(0, len(raw), 4):
        for channel in range(3):
            raw[i+channel] = (raw[i+channel]*raw[i+3]+127)//255
    target = name + '.rgba.gz'
    (root/target).write_bytes(gzip.compress(raw, mtime=0))
    records.append(dict(file=name, width=width, height=height, expected=target, tolerance=tolerance))

width, height = 259, 257
rgba = bytes(value for y in range(height) for x in range(width)
             for value in ((x*31)%256, (y*17)%256, (x+y)%256, [0, 1, 64, 128, 254, 255][(x+y)%6]))
(root/'alpha-tiles.png').write_bytes(png(width,height,rgba))
reference('alpha-tiles.png',width,height,rgba)

# All eight orientations share the same entropy-coded JPEG data.
image = Image.new('RGB', (23,17))
image.putdata([((x*7+y*3)%256,(x*2+y*11)%256,(x*9+y*5)%256) for y in range(17) for x in range(23)])
for orientation in range(1,9):
    exif = Image.Exif(); exif[274] = orientation
    name = f'orientation-{orientation}.jpg'
    image.save(root/name, quality=96, subsampling=0, exif=exif)
    with Image.open(root/name) as original:
        expected = ImageOps.exif_transpose(original).convert('RGBA')
        reference(name,*expected.size,expected.tobytes(),tolerance=3)

# Independent linear RGB ICC profile generated by LittleCMS, not Skia.
class xyY(c.Structure):
    _fields_ = [('x',c.c_double),('y',c.c_double),('Y',c.c_double)]
class Primaries(c.Structure):
    _fields_ = [('red',xyY),('green',xyY),('blue',xyY)]
library = next((Path(PIL.__file__).parent/'.dylibs').glob('liblcms2*.dylib'))
lib = c.CDLL(str(library))
lib.cmsBuildGamma.argtypes=[c.c_void_p,c.c_double]; lib.cmsBuildGamma.restype=c.c_void_p
lib.cmsCreateRGBProfile.argtypes=[c.POINTER(xyY),c.POINTER(Primaries),c.POINTER(c.c_void_p)];lib.cmsCreateRGBProfile.restype=c.c_void_p
lib.cmsSaveProfileToMem.argtypes=[c.c_void_p,c.c_void_p,c.POINTER(c.c_uint32)]
lib.cmsCloseProfile.argtypes=[c.c_void_p];lib.cmsFreeToneCurve.argtypes=[c.c_void_p]
curve=lib.cmsBuildGamma(None,1)
curves=(c.c_void_p*3)(curve,curve,curve)
profile=lib.cmsCreateRGBProfile(c.byref(xyY(.3127,.3290,1)),c.byref(Primaries(xyY(.64,.33,1),xyY(.30,.60,1),xyY(.15,.06,1))),curves)
size=c.c_uint32();assert lib.cmsSaveProfileToMem(profile,None,c.byref(size))
buffer=c.create_string_buffer(size.value);assert lib.cmsSaveProfileToMem(profile,buffer,c.byref(size))
profile_bytes=bytearray(buffer.raw)
# Fixed profile timestamp makes fixture regeneration deterministic.
profile_bytes[24:36]=struct.pack('>6H',2026,10,2,0,0,0)
lib.cmsCloseProfile(profile);lib.cmsFreeToneCurve(curve)
values=[0,1,16,64,128,192,254,255]
linear=bytes(channel for value in values for channel in (value,value,value,255))
def srgb(v):
    x=v/255
    return round(255*(12.92*x if x<=.0031308 else 1.055*x**(1/2.4)-.055))
expected=bytes(channel for value in values for channel in (srgb(value),)*3+(255,))
(root/'linear-profile.png').write_bytes(png(8,1,linear,profile_bytes))
reference('linear-profile.png',8,1,expected,1)
(root/'truncated.png').write_bytes((root/'alpha-tiles.png').read_bytes()[:100])
(root/'truncated.jpg').write_bytes((root/'orientation-1.jpg').read_bytes()[:700])
(root/'too-wide.png').write_bytes(png(30001,1,bytes(30001*4)))
(root/'too-many-pixels.png').write_bytes(png(10001,10000,b''))
Image.new('RGB',(2,2),'red').save(root/'unsupported.gif')
(root/'cases.json').write_text(json.dumps(records,indent=2)+'\n')
print(f'Generated {len(records)} reference cases and five invalid/unsupported inputs')
