from pathlib import Path
from PIL import Image
import numpy as np,json,hashlib,collections,shutil
b=Path('/Users/admin/.codex/visualizations/2026/09/20/01a0bf7d-45c7-7403-8411-eb985b4d9ff8/windows11-remote-suite');r=b/'window-visible-20260921-191109';e=Path('docs/windows/evidence/windows11-remote-suite/native-window');e.mkdir(exist_ok=True)
report=json.loads((r/'results/window-report.json').read_text());counts=collections.Counter(x['name'] for x in report['events']);assert counts['native-window-closed']==1 and not counts['action-error'];assert (r/'stderr.log').read_bytes()==b''
pairs=[]
for folder,a,c in [('001-text','preview.png','export.png'),('002-text','preview.png','export.png'),('003-brush','final.png','reopened.png'),('004-brush','final.png','reopened.png'),('005-composition','before.png','reopened.png')]:
 p=r/'results'/folder;x=np.array(Image.open(p/a).convert('RGBA'));y=np.array(Image.open(p/c).convert('RGBA'));assert np.array_equal(x,y);pairs.append({'save':folder,'rgbaExact':True})
review={'scope':'Actual native window and human-assisted selection evidence; not complete native IME/drag acceptance','archiveSha256':hashlib.sha256(r.with_suffix('.zip').read_bytes()).hexdigest(),'nativePreeditChanges':report['nativePreeditChanges'],'textInputEvents':report['textInputEvents'],'injectedInputMethodCalls':report['injectedInputMethodCalls'],'openedScaling':next(x['data']['scaling'] for x in report['events'] if x['name']=='native-window-opened'),'reportScalingAfterClose':report['renderScaling'],'scalingNote':'Read live scale from opened event; top-level report was written after close and returned default 1. No observed display-scale change.','events':dict(counts),'decodedPairs':pairs,'manualSelection':'User physically highlighted final 测试 in 中文1测试 at 150%, angle 0, not flipped. Screenshot confirmed two-character range. Pressing 1 yielded 中文11.','limitations':['CUA drag yielded no text selection; brush raw events contain only duplicate start points, not a continuous trajectory.','Keyboard delivery became intermittent; even Escape did not dismiss context menu, so subsequent Ctrl+Z nonresponse is not established as an editor bug.','Real Microsoft Pinyin candidate and commits observed. No-selection Escape restored displayed original. Select-all preedit then Escape removed original, and earlier Ctrl+Z restored it; needs isolated reproduction with text-state evidence.','Flipped manual drag, focus recovery, continuous brush/cancel, Qt native IME, remaining device matrix and full product acceptance pending.'],'closedNormally':True,'stderrEmpty':True}
(e/'review.json').write_text(json.dumps(review,ensure_ascii=False,indent=2)+'\n');shutil.copyfile(r/'results/window-report.json',e/'window-report.json')
for n in ['manual-selection-150-unflipped.png','manual-selection-replaced.png','ime-candidate-actual.png','composition-native-save-complete.png']:shutil.copyfile(b/'screenshots'/n,e/n)
print(json.dumps(review,ensure_ascii=False,indent=2))
