<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Compositor.Imaging/Compositor.Imaging.csproj" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.22" />
    <PackageReference Include="Avalonia.Themes.Simple" Version="11.3.22" />
    <AvaloniaResource Include="../../Compositor/Resources/Fonts/SourceHanSansSC-Regular.otf" Link="Fonts/SourceHanSansSC-Regular.otf" />
    <None Include="../../Compositor/Resources/Licenses/SourceHanSans-OFL.txt" Link="Licenses/SourceHanSans-OFL.txt" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
